{{- if and .Values.persistence.enabled (not .Values.persistence.storageClass) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "project.name" . }}
  labels:
    app: {{ include "project.name" . }}
    appGroup: {{ .Values.global.appGroup }}
    chart: {{ include "project.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
  - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.persistentVolumeReclaimPolicy | default "Retain" | quote }}
{{ toYaml .Values.persistence.pv | indent 2 }}
{{- end }}
