CREATE TABLE DEMO_ORDER_DETAIL (
	ITEM_ID VARCHAR2(50) NOT NULL,
	ITEM_CODE VARCHAR2(50) NOT NULL,
	ITEM_NAME VARCHAR2(50),
	ORDER_ID VARCHAR(50) NOT NULL,
	UPDATE_DATE TIMESTAMP,
	PRIMARY KEY ("ITEM_ID")
);

COMMENT ON COLUMN DEMO_ORDER_DETAIL.ITEM_ID IS '记录ID';
COMMENT ON COLUMN DEMO_ORDER_DETAIL.ITEM_CODE IS '商品代码';
COMMENT ON COLUMN DEMO_ORDER_DETAIL.ITEM_NAME IS '商品名称';
COMMENT ON COLUMN DEMO_ORDER_DETAIL.ORDER_ID IS '商品名称';
COMMENT ON COLUMN DEMO_ORDER_DETAIL.UPDATE_DATE IS '修改时间';